### ISSUE TITLE
Show a message saying `invalid` graphql endpoint if it cannot introspect

### ISSUE THREAD

**Issue by karthikvt26** [hasura/graphqurl#18]
➜  ~ gq http://localhost:8080

Error: Network error: Unexpected token N in JSON at position 0
    at new ApolloError (~/.nvm/versions/node/v10.1.0/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:124:32)
    at ~/.nvm/versions/node/v10.1.0/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:1248:45
    at ~/.nvm/versions/node/v10.1.0/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:1680:21
    at Array.forEach (<anonymous>)
    at ~/.nvm/versions/node/v10.1.0/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:1679:22
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (~/.nvm/versions/node/v10.1.0/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:1672:26)
    at ~/.nvm/versions/node/v10.1.0/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:1175:35

Expectation: Invalid GraphQL endpoint.

**Comment by UtkarshGupta-CS** [comment]
@karthikvt26 Is `http://localhost:8080/` your graphql endpoint? 

Usually, you can set custom graphql endpoint like `http://localhost:8080/graphql` or `http://localhost:8080/graphqlApi` ?

**Comment by chtnnh** [comment]
Gentle ping @ShraddhaAg
