### ISSUE TITLE
Throws exception after installation for any command

### ISSUE THREAD

**Issue by alaptseu** [hasura/graphqurl#22]
gq -h 
`/usr/local/lib/node_modules/graphqurl/src/command.js:16
  async run() {
        ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/graphqurl/bin/run:3:1)
    at Module._compile (module.js:573:32)`

**Comment by shahidhk** [comment]
@alaptseu What is the node version and OS? We have tested on v8.0.0 and above

**Comment by alaptseu** [comment]
@shahidhk yes, the issue was when I had node v7.1.0, I've upgraded to v10.9.0 and it works fine now. Thanks!
