### ISSUE TITLE
[bug,ci] does not work on node v8.0.0

### ISSUE THREAD

**Issue by shouldsee** [hasura/graphqurl#58]
though package.json specify node>=8.0.0, the installed cli failed on 8.0.0 with command

```
$ node -v
v8.0.0
$ npm -v
5.0.0
$ gq
/home/user/.nvm/versions/node/v8.0.0/lib/node_modules/graphqurl/node_modules/graphql-language-service-parser/dist/onlineParser.js:128
    state.prevState = { ...state };
                        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v8.0.0/lib/node_modules/graphqurl/node_modules/graphql-language-service-parser/dist/index.js:15:22)

```

However, the error disappear once switched to node==10.0.0. Should this be reflected somewhere in the CI yaml config?

**Comment by manasag** [comment]
Closing this as node8 is not supported anymore. Library now supports node v18+
